# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rhubarb"
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["William Benton"]
  s.date = "2012-02-09"
  s.description = "Rhubarb is a simple object-graph persistence library implemented as a mixin.  It also works with the SPQR library for straightforward object publishing over QMF."
  s.email = "willb@redhat.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    "CHANGES",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/rhubarb/classmixins.rb",
    "lib/rhubarb/column.rb",
    "lib/rhubarb/mixins/freshness.rb",
    "lib/rhubarb/persistence.rb",
    "lib/rhubarb/persisting.rb",
    "lib/rhubarb/reference.rb",
    "lib/rhubarb/rhubarb.rb",
    "lib/rhubarb/util.rb",
    "ruby-rhubarb.spec.in",
    "test/helper.rb",
    "test/test_rhubarb.rb"
  ]
  s.homepage = "http://git.fedorahosted.org/git/grid/rhubarb.git"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rhubarb:  object graph persistence, easy as pie"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 1.2.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.2"])
  end
end

