# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rhubarb}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["William Benton"]
  s.date = %q{2011-07-06}
  s.description = %q{Rhubarb is a simple object-graph persistence library implemented as a mixin.  It also works with the SPQR library for straightforward object publishing over QMF.}
  s.email = %q{willb@redhat.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    "CHANGES",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/rhubarb/classmixins.rb",
    "lib/rhubarb/column.rb",
    "lib/rhubarb/mixins/freshness.rb",
    "lib/rhubarb/persistence.rb",
    "lib/rhubarb/persisting.rb",
    "lib/rhubarb/reference.rb",
    "lib/rhubarb/rhubarb.rb",
    "lib/rhubarb/util.rb",
    "ruby-rhubarb.spec.in",
    "test/helper.rb",
    "test/test_rhubarb.rb"
  ]
  s.homepage = %q{http://git.fedorahosted.org/git/grid/rhubarb.git}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rhubarb:  object graph persistence, easy as pie}
  s.test_files = [
    "test/helper.rb",
    "test/test_rhubarb.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 1.2.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.2"])
  end
end

